# .bashrc

export DOTFILES=$HOME/.dotfiles

if [ -n "$DISPLAY"  ]; then
  xset b off
fi

function source_files() {
  local file

  for file in $DOTFILES/shell/*.sh; do
    source ${file}
  done

  for file in $DOTFILES/shell/bash/*.sh; do
    source ${file}
  done
}

if [[ -f ~/.shell.flags ]]; then
  source ~/.shell.flags
fi

source_files

if [[ -f ~/.bashrc.local ]]; then
  source ~/.bashrc.local
fi

if [[ -d /etc/profile.d/ ]]; then
  for file in $( ls /etc/profile.d/*.sh ); do
    source ${file}
  done
fi