# .zshrc

function source_files() {
  local file

  for file in $DOTFILES/shell/*.sh; do
    source ${file}
  done

  for file in $DOTFILES/shell/zsh/*.zsh; do
    source ${file}
  done
}

if [[ -f ~/.shell.flags ]]; then
  source ~/.shell.flags
fi

source_files

if [[ -f ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi

if [[ -d /etc/profile.d/ ]]; then
  for file in $( ls /etc/profile.d/*.sh ); do
    source ${file}
  done
fi